var hierarchy =
[
    [ "exception", null, [
      [ "netCDF::exceptions::NcException", "classnetCDF_1_1exceptions_1_1NcException.html", [
        [ "netCDF::exceptions::NcAttExists", "classnetCDF_1_1exceptions_1_1NcAttExists.html", null ],
        [ "netCDF::exceptions::NcAttMeta", "classnetCDF_1_1exceptions_1_1NcAttMeta.html", null ],
        [ "netCDF::exceptions::NcBadDim", "classnetCDF_1_1exceptions_1_1NcBadDim.html", null ],
        [ "netCDF::exceptions::NcBadFieldId", "classnetCDF_1_1exceptions_1_1NcBadFieldId.html", null ],
        [ "netCDF::exceptions::NcBadGroupId", "classnetCDF_1_1exceptions_1_1NcBadGroupId.html", null ],
        [ "netCDF::exceptions::NcBadId", "classnetCDF_1_1exceptions_1_1NcBadId.html", null ],
        [ "netCDF::exceptions::NcBadName", "classnetCDF_1_1exceptions_1_1NcBadName.html", null ],
        [ "netCDF::exceptions::NcBadType", "classnetCDF_1_1exceptions_1_1NcBadType.html", null ],
        [ "netCDF::exceptions::NcBadTypeId", "classnetCDF_1_1exceptions_1_1NcBadTypeId.html", null ],
        [ "netCDF::exceptions::NcCantCreate", "classnetCDF_1_1exceptions_1_1NcCantCreate.html", null ],
        [ "netCDF::exceptions::NcCantRead", "classnetCDF_1_1exceptions_1_1NcCantRead.html", null ],
        [ "netCDF::exceptions::NcCantWrite", "classnetCDF_1_1exceptions_1_1NcCantWrite.html", null ],
        [ "netCDF::exceptions::NcChar", "classnetCDF_1_1exceptions_1_1NcChar.html", null ],
        [ "netCDF::exceptions::NcDimMeta", "classnetCDF_1_1exceptions_1_1NcDimMeta.html", null ],
        [ "netCDF::exceptions::NcDimSize", "classnetCDF_1_1exceptions_1_1NcDimSize.html", null ],
        [ "netCDF::exceptions::NcEdge", "classnetCDF_1_1exceptions_1_1NcEdge.html", null ],
        [ "netCDF::exceptions::NcElateDef", "classnetCDF_1_1exceptions_1_1NcElateDef.html", null ],
        [ "netCDF::exceptions::NcEnoGrp", "classnetCDF_1_1exceptions_1_1NcEnoGrp.html", null ],
        [ "netCDF::exceptions::NcExist", "classnetCDF_1_1exceptions_1_1NcExist.html", null ],
        [ "netCDF::exceptions::NcFileMeta", "classnetCDF_1_1exceptions_1_1NcFileMeta.html", null ],
        [ "netCDF::exceptions::NcGlobal", "classnetCDF_1_1exceptions_1_1NcGlobal.html", null ],
        [ "netCDF::exceptions::NcHdfErr", "classnetCDF_1_1exceptions_1_1NcHdfErr.html", null ],
        [ "netCDF::exceptions::NcInDefineMode", "classnetCDF_1_1exceptions_1_1NcInDefineMode.html", null ],
        [ "netCDF::exceptions::NcInvalidArg", "classnetCDF_1_1exceptions_1_1NcInvalidArg.html", null ],
        [ "netCDF::exceptions::NcInvalidCoords", "classnetCDF_1_1exceptions_1_1NcInvalidCoords.html", null ],
        [ "netCDF::exceptions::NcInvalidWrite", "classnetCDF_1_1exceptions_1_1NcInvalidWrite.html", null ],
        [ "netCDF::exceptions::NcMaxAtts", "classnetCDF_1_1exceptions_1_1NcMaxAtts.html", null ],
        [ "netCDF::exceptions::NcMaxDims", "classnetCDF_1_1exceptions_1_1NcMaxDims.html", null ],
        [ "netCDF::exceptions::NcMaxName", "classnetCDF_1_1exceptions_1_1NcMaxName.html", null ],
        [ "netCDF::exceptions::NcMaxVars", "classnetCDF_1_1exceptions_1_1NcMaxVars.html", null ],
        [ "netCDF::exceptions::NcNameInUse", "classnetCDF_1_1exceptions_1_1NcNameInUse.html", null ],
        [ "netCDF::exceptions::NcNFile", "classnetCDF_1_1exceptions_1_1NcNFile.html", null ],
        [ "netCDF::exceptions::NcNoCompound", "classnetCDF_1_1exceptions_1_1NcNoCompound.html", null ],
        [ "netCDF::exceptions::NcNoMem", "classnetCDF_1_1exceptions_1_1NcNoMem.html", null ],
        [ "netCDF::exceptions::NcNoRecVars", "classnetCDF_1_1exceptions_1_1NcNoRecVars.html", null ],
        [ "netCDF::exceptions::NcNotAtt", "classnetCDF_1_1exceptions_1_1NcNotAtt.html", null ],
        [ "netCDF::exceptions::NcNotInDefineMode", "classnetCDF_1_1exceptions_1_1NcNotInDefineMode.html", null ],
        [ "netCDF::exceptions::NcNotNc4", "classnetCDF_1_1exceptions_1_1NcNotNc4.html", null ],
        [ "netCDF::exceptions::NcNotNCF", "classnetCDF_1_1exceptions_1_1NcNotNCF.html", null ],
        [ "netCDF::exceptions::NcNotVar", "classnetCDF_1_1exceptions_1_1NcNotVar.html", null ],
        [ "netCDF::exceptions::NcNullDim", "classnetCDF_1_1exceptions_1_1NcNullDim.html", null ],
        [ "netCDF::exceptions::NcNullGrp", "classnetCDF_1_1exceptions_1_1NcNullGrp.html", null ],
        [ "netCDF::exceptions::NcNullType", "classnetCDF_1_1exceptions_1_1NcNullType.html", null ],
        [ "netCDF::exceptions::NcRange", "classnetCDF_1_1exceptions_1_1NcRange.html", null ],
        [ "netCDF::exceptions::NcStrictNc3", "classnetCDF_1_1exceptions_1_1NcStrictNc3.html", null ],
        [ "netCDF::exceptions::NcStride", "classnetCDF_1_1exceptions_1_1NcStride.html", null ],
        [ "netCDF::exceptions::NcSts", "classnetCDF_1_1exceptions_1_1NcSts.html", null ],
        [ "netCDF::exceptions::NcTrunc", "classnetCDF_1_1exceptions_1_1NcTrunc.html", null ],
        [ "netCDF::exceptions::NcUnknownName", "classnetCDF_1_1exceptions_1_1NcUnknownName.html", null ],
        [ "netCDF::exceptions::NcUnlimit", "classnetCDF_1_1exceptions_1_1NcUnlimit.html", null ],
        [ "netCDF::exceptions::NcUnlimPos", "classnetCDF_1_1exceptions_1_1NcUnlimPos.html", null ],
        [ "netCDF::exceptions::NcVarMeta", "classnetCDF_1_1exceptions_1_1NcVarMeta.html", null ],
        [ "netCDF::exceptions::NcVarSize", "classnetCDF_1_1exceptions_1_1NcVarSize.html", null ]
      ] ]
    ] ],
    [ "netCDF::NcAtt", "classnetCDF_1_1NcAtt.html", [
      [ "netCDF::NcGroupAtt", "classnetCDF_1_1NcGroupAtt.html", null ],
      [ "netCDF::NcVarAtt", "classnetCDF_1_1NcVarAtt.html", null ]
    ] ],
    [ "netCDF::NcDim", "classnetCDF_1_1NcDim.html", null ],
    [ "netCDF::NcGroup", "classnetCDF_1_1NcGroup.html", [
      [ "netCDF::NcFile", "classnetCDF_1_1NcFile.html", null ]
    ] ],
    [ "netCDF::NcType", "classnetCDF_1_1NcType.html", [
      [ "netCDF::NcByte", "classnetCDF_1_1NcByte.html", null ],
      [ "netCDF::NcChar", "classnetCDF_1_1NcChar.html", null ],
      [ "netCDF::NcCompoundType", "classnetCDF_1_1NcCompoundType.html", null ],
      [ "netCDF::NcDouble", "classnetCDF_1_1NcDouble.html", null ],
      [ "netCDF::NcEnumType", "classnetCDF_1_1NcEnumType.html", null ],
      [ "netCDF::NcFloat", "classnetCDF_1_1NcFloat.html", null ],
      [ "netCDF::NcInt", "classnetCDF_1_1NcInt.html", null ],
      [ "netCDF::NcInt64", "classnetCDF_1_1NcInt64.html", null ],
      [ "netCDF::NcOpaqueType", "classnetCDF_1_1NcOpaqueType.html", null ],
      [ "netCDF::NcShort", "classnetCDF_1_1NcShort.html", null ],
      [ "netCDF::NcString", "classnetCDF_1_1NcString.html", null ],
      [ "netCDF::NcUbyte", "classnetCDF_1_1NcUbyte.html", null ],
      [ "netCDF::NcUint", "classnetCDF_1_1NcUint.html", null ],
      [ "netCDF::NcUint64", "classnetCDF_1_1NcUint64.html", null ],
      [ "netCDF::NcUshort", "classnetCDF_1_1NcUshort.html", null ],
      [ "netCDF::NcVlenType", "classnetCDF_1_1NcVlenType.html", null ]
    ] ],
    [ "netCDF::NcVar", "classnetCDF_1_1NcVar.html", null ]
];