var namespacenetCDF =
[
    [ "exceptions", "namespacenetCDF_1_1exceptions.html", "namespacenetCDF_1_1exceptions" ],
    [ "NcAtt", "classnetCDF_1_1NcAtt.html", "classnetCDF_1_1NcAtt" ],
    [ "NcByte", "classnetCDF_1_1NcByte.html", "classnetCDF_1_1NcByte" ],
    [ "NcChar", "classnetCDF_1_1NcChar.html", "classnetCDF_1_1NcChar" ],
    [ "NcCompoundType", "classnetCDF_1_1NcCompoundType.html", "classnetCDF_1_1NcCompoundType" ],
    [ "NcDim", "classnetCDF_1_1NcDim.html", "classnetCDF_1_1NcDim" ],
    [ "NcDouble", "classnetCDF_1_1NcDouble.html", "classnetCDF_1_1NcDouble" ],
    [ "NcEnumType", "classnetCDF_1_1NcEnumType.html", "classnetCDF_1_1NcEnumType" ],
    [ "NcFile", "classnetCDF_1_1NcFile.html", "classnetCDF_1_1NcFile" ],
    [ "NcFloat", "classnetCDF_1_1NcFloat.html", "classnetCDF_1_1NcFloat" ],
    [ "NcGroup", "classnetCDF_1_1NcGroup.html", "classnetCDF_1_1NcGroup" ],
    [ "NcGroupAtt", "classnetCDF_1_1NcGroupAtt.html", "classnetCDF_1_1NcGroupAtt" ],
    [ "NcInt", "classnetCDF_1_1NcInt.html", "classnetCDF_1_1NcInt" ],
    [ "NcInt64", "classnetCDF_1_1NcInt64.html", "classnetCDF_1_1NcInt64" ],
    [ "NcOpaqueType", "classnetCDF_1_1NcOpaqueType.html", "classnetCDF_1_1NcOpaqueType" ],
    [ "NcShort", "classnetCDF_1_1NcShort.html", "classnetCDF_1_1NcShort" ],
    [ "NcString", "classnetCDF_1_1NcString.html", "classnetCDF_1_1NcString" ],
    [ "NcType", "classnetCDF_1_1NcType.html", "classnetCDF_1_1NcType" ],
    [ "NcUbyte", "classnetCDF_1_1NcUbyte.html", "classnetCDF_1_1NcUbyte" ],
    [ "NcUint", "classnetCDF_1_1NcUint.html", "classnetCDF_1_1NcUint" ],
    [ "NcUint64", "classnetCDF_1_1NcUint64.html", "classnetCDF_1_1NcUint64" ],
    [ "NcUshort", "classnetCDF_1_1NcUshort.html", "classnetCDF_1_1NcUshort" ],
    [ "NcVar", "classnetCDF_1_1NcVar.html", "classnetCDF_1_1NcVar" ],
    [ "NcVarAtt", "classnetCDF_1_1NcVarAtt.html", "classnetCDF_1_1NcVarAtt" ],
    [ "NcVlenType", "classnetCDF_1_1NcVlenType.html", "classnetCDF_1_1NcVlenType" ]
];